### ISSUE TITLE
B_StartOtherRoutine

### ISSUE THREAD

**Issue by Fabiosek** [kirides/vscode-daedalus#5]
There is no autocomplete for B_StartOtherRoutine.

**Comment by kirides** [comment]
![image](https://user-images.githubusercontent.com/13602143/160275533-96a1d0fd-436b-47a7-91bc-9e36138eddae.png)
![image](https://user-images.githubusercontent.com/13602143/160275541-914a1597-2c5f-4071-b92b-86972dac92c3.png)

Can't reproduce it, works fine here :/
